---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mssql-gateway
  namespace: mssql
spec:
  gatewayClassName: traefik
  listeners:
    - name: mssql
      protocol: TCP
      port: 1433
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: mssql-tcp
  namespace: mssql
spec:
  parentRefs:
    - name: mssql-gateway
      sectionName: mssql
      kind: Gateway
  rules:
     - backendRefs:
        - name: mssql-service
          namespace: mssql
          port: 1433
