apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    k8s-app: busybox
  name: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: busybox
  template:
    metadata:
      labels:
        k8s-app: busybox
    spec:
      containers:
      - image: busybox
        imagePullPolicy: Always
        name: busybox
        command: ["tail", "-f", "/dev/null"]
        