---
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-configmap
  namespace: hive
data:
  CORE_CONF_fs_defaultFS: hdfs://namenode.hadoop:9000
  CORE_CONF_hadoop_http_staticuser_user: root
  CORE_CONF_io_compression_codecs: org.apache.hadoop.io.compress.SnappyCodec

  HDFS_CONF_dfs_webhdfs_enabled: 'true'
  HDFS_CONF_dfs_permissions_enabled: 'false'
  HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: 'false'

  HDFS_CONF_dfs_client_use_datanode_hostname: 'false'
  HDFS_CONF_dfs_datanode_use_datanode_hostname: 'false'

  TEZ_CONF_tez_lib_uris: hdfs://namenode.hadoop:9000/apps/tez-0.10.2/tez-0.10.2-minimal.tar.gz
  TEZ_CONF_tez_use_cluster_hadoop___libs: 'false' 

  YARN_CONF_yarn_log___aggregation___enable: 'true'
  YARN_CONF_yarn_log_server_url: http://yarn.hadoop:8188/applicationhistory/logs/
  YARN_CONF_yarn_resourcemanager_recovery_enabled: 'true'
  YARN_CONF_yarn_resourcemanager_store_class: org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
  YARN_CONF_yarn_resourcemanager_scheduler_class: org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler
  # YARN_CONF_yarn_resourcemanager_scheduler_class: org.apache.hadoop.yarn.server.resourcemanager.scheduler.fair.FairScheduler
  YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___mb: '8192'
  YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___vcores: '4'
  YARN_CONF_yarn_resourcemanager_fs_state___store_uri: /rmstate
  YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled: 'true'
  YARN_CONF_yarn_timeline___service_enabled: 'true'
  YARN_CONF_yarn_timeline___service_generic___application___history_enabled: 'true'
  YARN_CONF_mapreduce_map_output_compress: 'true'
  YARN_CONF_mapred_map_output_compress_codec: org.apache.hadoop.io.compress.SnappyCodec
  YARN_CONF_yarn_nodemanager_resource_memory___mb: '16384'
  YARN_CONF_yarn_nodemanager_resource_cpu___vcores: '8'
  YARN_CONF_yarn_nodemanager_disk___health___checker_max___disk___utilization___per___disk___percentage: '98.5'
  YARN_CONF_yarn_nodemanager_remote___app___log___dir: /app-logs
  YARN_CONF_yarn_nodemanager_aux___services: mapreduce_shuffle

  MAPRED_CONF_mapreduce_framework_name: yarn
  MAPRED_CONF_mapred_child_java_opts: -Xmx4096m
  MAPRED_CONF_mapreduce_map_memory_mb: '4096'
  MAPRED_CONF_mapreduce_reduce_memory_mb: '8192'
  MAPRED_CONF_mapreduce_map_java_opts: -Xmx3072m
  MAPRED_CONF_mapreduce_reduce_java_opts: -Xmx6144m

  HIVE_CONF_javax_jdo_option_ConnectionDriverName: org.postgresql.Driver
  HIVE_CONF_javax_jdo_option_ConnectionURL: jdbc:postgresql://postgis-service.postgis:5432/hive_metastore
  HIVE_CONF_javax_jdo_option_ConnectionUserName: hive
  HIVE_CONF_javax_jdo_option_ConnectionPassword: metastore
  HIVE_CONF_hive_metastore_warehouse_dir: /hive/warehouse/data
  HIVE_CONF_hive_server2_enable_doAs: 'false'
  HIVE_CONF_hive_users_in_admin_role: root
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hive4-core-configmap
  namespace: hive
data:
  CORE_CONF_fs_defaultFS: hdfs://namenode.hadoop:9000
  CORE_CONF_hadoop_http_staticuser_user: root
  CORE_CONF_io_compression_codecs: org.apache.hadoop.io.compress.SnappyCodec

  HDFS_CONF_dfs_webhdfs_enabled: 'true'
  HDFS_CONF_dfs_permissions_enabled: 'false'
  HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: 'false'

  HDFS_CONF_dfs_client_use_datanode_hostname: 'false'
  HDFS_CONF_dfs_datanode_use_datanode_hostname: 'false'

  TEZ_CONF_tez_lib_uris: hdfs://namenode.hadoop:9000/apps/tez-0.10.5/tez-0.10.5-minimal.tar.gz
  TEZ_CONF_tez_use_cluster_hadoop___libs: 'false' 

  YARN_CONF_yarn_log___aggregation___enable: 'true'
  YARN_CONF_yarn_log_server_url: http://yarn.hadoop:8188/applicationhistory/logs/
  YARN_CONF_yarn_resourcemanager_recovery_enabled: 'true'
  YARN_CONF_yarn_resourcemanager_store_class: org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
  YARN_CONF_yarn_resourcemanager_scheduler_class: org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler
  # YARN_CONF_yarn_resourcemanager_scheduler_class: org.apache.hadoop.yarn.server.resourcemanager.scheduler.fair.FairScheduler
  YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___mb: '8192'
  YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___vcores: '4'
  YARN_CONF_yarn_resourcemanager_fs_state___store_uri: /rmstate
  YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled: 'true'
  YARN_CONF_yarn_timeline___service_enabled: 'true'
  YARN_CONF_yarn_timeline___service_generic___application___history_enabled: 'true'
  YARN_CONF_mapreduce_map_output_compress: 'true'
  YARN_CONF_mapred_map_output_compress_codec: org.apache.hadoop.io.compress.SnappyCodec
  YARN_CONF_yarn_nodemanager_resource_memory___mb: '16384'
  YARN_CONF_yarn_nodemanager_resource_cpu___vcores: '8'
  YARN_CONF_yarn_nodemanager_disk___health___checker_max___disk___utilization___per___disk___percentage: '98.5'
  YARN_CONF_yarn_nodemanager_remote___app___log___dir: /app-logs
  YARN_CONF_yarn_nodemanager_aux___services: mapreduce_shuffle

  MAPRED_CONF_mapreduce_framework_name: yarn
  MAPRED_CONF_mapred_child_java_opts: -Xmx4096m
  MAPRED_CONF_mapreduce_map_memory_mb: '4096'
  MAPRED_CONF_mapreduce_reduce_memory_mb: '8192'
  MAPRED_CONF_mapreduce_map_java_opts: -Xmx3072m
  MAPRED_CONF_mapreduce_reduce_java_opts: -Xmx6144m

  HIVE_CONF_javax_jdo_option_ConnectionDriverName: org.postgresql.Driver
  HIVE_CONF_javax_jdo_option_ConnectionURL: jdbc:postgresql://postgis-service.postgis:5432/hive4_metastore
  HIVE_CONF_javax_jdo_option_ConnectionUserName: hive
  HIVE_CONF_javax_jdo_option_ConnectionPassword: metastore
  HIVE_CONF_hive_metastore_warehouse_dir: /hive/warehouse/data
  HIVE_CONF_hive_server2_enable_doAs: 'false'
  HIVE_CONF_hive_users_in_admin_role: root
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metastore-configmap
  namespace: hive
data:
  HIVEMETASTORE_CONF_metastore_metastore_event_db_notification_api_auth: 'false'
  HIVEMETASTORE_CONF_hive_security_metastore_authorization_manager: org.apache.hadoop.hive.ql.security.authorization.MetaStoreAuthzAPIAuthorizerEmbedOnly
  HIVEMETASTORE_CONF_hive_security_authorization_manager: org.apache.hadoop.hive.ql.security.authorization.plugin.sqlstd.SQLStdConfOnlyAuthorizerFactory

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hiveserver2-configmap
  namespace: hive
data:
  HIVESERVER2_CONF_hive_metastore_uris: thrift://metastore.hive:9083
  HIVESERVER2_CONF_hive_security_authorization_enabled: 'false'
  # HIVESERVER2_CONF_hive_security_authorization_enabled: 'true'
  HIVESERVER2_CONF_hive_security_authorization_manager: org.apache.hadoop.hive.ql.security.authorization.plugin.sqlstd.SQLStdHiveAuthorizerFactory
  HIVESERVER2_CONF_hive_security_authenticator_manager: org.apache.hadoop.hive.ql.security.SessionStateUserAuthenticator

  # HIVESERVER2_CONF_hive_server2_authentication: PAM
  # HIVESERVER2_CONF_hive_server2_authentication_pam_services: login

  # HIVESERVER2_CONF_hive_server2_authentication: LDAP
  # HIVESERVER2_CONF_hive_server2_authentication_ldap_url: ldap://ldap
  # HIVESERVER2_CONF_hive_server2_authentication_ldap_baseDN: "dc=ldap"

  HIVESERVER2_CONF_hive_txn_manager: org.apache.hadoop.hive.ql.lockmgr.DbTxnManager
  HIVESERVER2_CONF_hive_support_concurrency: 'true'
  HIVESERVER2_CONF_hive_zookeeper_quorum: zookeeper.zookeeper:2181

  HIVESERVER2_CONF_hive_tez_exec_inplace_progress: 'false'
  HIVESERVER2_CONF_hive_exec_scratchdir: /hive/scratch_dir
  HIVESERVER2_CONF_hive_user_install_directory: /hive/install_dir
  HIVESERVER2_CONF_hive_exec_submit_local_task_via_child: 'false'
  HIVESERVER2_CONF_mapreduce_framework_name: hive
  HIVESERVER2_CONF_hive_execution_engine: tez
