---
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-configmap
  namespace: hive
data:
  CORE_CONF_fs_defaultFS: hdfs://namenode.hadoop:9000
  CORE_CONF_hadoop_http_staticuser_user: root

  HDFS_CONF_dfs_client_use_datanode_hostname: 'true'
  HDFS_CONF_dfs_datanode_use_datanode_hostname: 'true'

  TEZ_CONF_tez_lib_uris: hdfs://namenode.hadoop:9000/apps/tez-0.10.5/tez-0.10.5-minimal.tar.gz
  TEZ_CONF_tez_use_cluster_hadoop___libs: 'false' 

  HIVE_CONF_javax_jdo_option_ConnectionDriverName: org.postgresql.Driver
  HIVE_CONF_javax_jdo_option_ConnectionURL: jdbc:postgresql://postgis-service.postgis:5432/hive4_metastore
  HIVE_CONF_javax_jdo_option_ConnectionUserName: hive
  HIVE_CONF_javax_jdo_option_ConnectionPassword: metastore
  HIVE_CONF_hive_metastore_warehouse_dir: /hive/warehouse/data
  HIVE_CONF_hive_server2_enable_doAs: 'false'
  HIVE_CONF_hive_users_in_admin_role: root

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metastore-configmap
  namespace: hive
data:
  HIVEMETASTORE_CONF_hive_metastore_event_db_notification_api_auth: 'false'
  HIVEMETASTORE_CONF_hive_security_metastore_authorization_manager: org.apache.hadoop.hive.ql.security.authorization.MetaStoreAuthzAPIAuthorizerEmbedOnly
  HIVEMETASTORE_CONF_hive_security_authorization_manager: org.apache.hadoop.hive.ql.security.authorization.plugin.sqlstd.SQLStdConfOnlyAuthorizerFactory

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hiveserver2-configmap
  namespace: hive
data:
  HIVESERVER2_CONF_hive_metastore_uris: thrift://metastore.hive:9083
  
  # HIVESERVER2_CONF_hive_security_authorization_enabled: 'true'
  # HIVESERVER2_CONF_hive_security_authorization_manager: org.apache.hadoop.hive.ql.security.authorization.plugin.sqlstd.SQLStdHiveAuthorizerFactory
  # HIVESERVER2_CONF_hive_security_authenticator_manager: org.apache.hadoop.hive.ql.security.SessionStateUserAuthenticator

  HIVESERVER2_CONF_hive_server2_authentication: NONE

  # HIVESERVER2_CONF_hive_server2_authentication: PAM
  # HIVESERVER2_CONF_hive_server2_authentication_pam_services: login

  # HIVESERVER2_CONF_hive_server2_authentication: LDAP
  # HIVESERVER2_CONF_hive_server2_authentication_ldap_url: ldap://ldap
  # HIVESERVER2_CONF_hive_server2_authentication_ldap_baseDN: "dc=ldap"

  HIVESERVER2_CONF_hive_txn_manager: org.apache.hadoop.hive.ql.lockmgr.DbTxnManager
  HIVESERVER2_CONF_hive_support_concurrency: 'true'
  HIVESERVER2_CONF_hive_zookeeper_quorum: zookeeper.zookeeper:2181

  HIVESERVER2_CONF_hive_tez_exec_inplace_progress: 'false'
  HIVESERVER2_CONF_hive_exec_scratchdir: /hive/scratch_dir
  HIVESERVER2_CONF_hive_user_install_directory: /hive/install_dir
  HIVESERVER2_CONF_hive_exec_submit_local_task_via_child: 'false'
  HIVESERVER2_CONF_mapreduce_framework_name: hive
  HIVESERVER2_CONF_hive_execution_engine: tez

  HIVESERVER2_CONF_hive_server2_webui_port: '80'