---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: upgradeschema
  name: upgradeschema
  namespace: hive
spec:
  selector:
    matchLabels:
      app: upgradeschema
  template:
    metadata:
      labels:
        app: upgradeschema
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: upgradeschema
        - name: DB_DRIVER
          value: postgres
        envFrom:
        - configMapRef:
            name: core-configmap
        image: localhost:5000/hive:4.1.0
        imagePullPolicy: Always
        name: upgradeschema
