apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv
  namespace: docker-registry
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: docker-registry
    name: docker-registry-pvc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /run/desktop/mnt/host/d/db/registry
    type: Directory