---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: postgis-gateway
  namespace: postgis
spec:
  gatewayClassName: traefik
  listeners:
    - name: postgis
      protocol: TCP
      port: 5432
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: postgis-tcp
  namespace: postgis
spec:
  parentRefs:
    - name: postgis-gateway
      sectionName: postgis
      kind: Gateway
  rules:
     - backendRefs:
        - name: postgis-service
          namespace: postgis
          port: 5432
